export const FETCH_GAMES_REQUEST = 'FETCH_GAMES_REQUEST';
export const FETCH_GAMES_SUCCESS = 'FETCH_GAMES_SUCCESS';

export const UPDATE_SEARCH_CONDITION = 'UPDATE_SEARCH_CONDITION';
export const UPDATE_GENRE_CONDITION = 'UPDATE_GENRE_CONDITION';
export const UPDATE_SORT_CONDITION = 'UPDATE_SORT_CONDITION';
export const FETCH_GENRES_REQUEST = 'FETCH_GENRES_REQUEST';
export const FETCH_GENRES_SUCCESS = 'FETCH_GENRES_SUCCESS';
